# https://hub.docker.com/_/ubuntu
# The ubuntu:latest tag points to the "latest LTS"
image: ubuntu:latest

pages:
  stage: deploy
  script:
  # https://rtfm.co.ua/en/docker-configure-tzdata-and-timezone-during-build/
  # https://askubuntu.com/a/1098881
  - export TZ=Asia/Taipei
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  # https://stackoverflow.com/a/58072486
  - apt-get update
  - apt-get install -y wget make git gettext
  #- make clone_pali_data
  - make download_go
  - make install
  - make po2mo
  - make dir
  - make html
  - make js
  # The following line will make page deploy job fail (but build ok)
  #- make symlink
  - mv website/ public/
  - "echo -e 'User-agent: *\nDisallow: /' > public/robots.txt"
  artifacts:
    paths:
    - public/
  only:
  - master
