# https://hub.docker.com/_/ubuntu
# The ubuntu:latest tag points to the "latest LTS"
image: ubuntu:latest

pages:
  stage: deploy
  script:
  # https://stackoverflow.com/a/58072486
  - apt-get update
  - apt-get install -y wget make
  - make clone_pali_data
  - make download_go
  - make install
  - make po2mo
  - make dir
  - make html
  - make scss
  - make js
  - make symlink
  - mv website/ public/
  - "echo -e 'User-agent: *\nDisallow: /' > public/robots.txt"
  artifacts:
    paths:
    - public/
  only:
  - master
