dist: bionic
language: go
go:
  - 1.12.17
addons:
  apt:
    packages:
    - wget
    - make
    - git
    - gettext
install:
  - make install
script:
  - make po2mo
  # build website/ content for dictionary.online-dhamma.net
  - make dir
  - make htmldhamma
  - make js
  - make about_symlink
  # move dictionary.online-dhamma.net to website2/
  - mv website/ website2
  # build website/ content for dictionary.sutta.org
  - make dir
  - make htmlsutta
  - make js
  - make about_symlink
deploy:
  - provider: pages
    repo: siongui/dictionary.online-dhamma.net
    fqdn: dictionary.online-dhamma.net
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    local_dir: website2
    on:
      branch: master
  - provider: pages
    repo: siongui/dictionary.sutta.org
    fqdn: dictionary.sutta.org
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    local_dir: website
    on:
      branch: master
