language: go
install:
  - go get github.com/siongui/gopalilib/dicutil
  - go get github.com/wellington/go-libsass
  - go get github.com/siongui/go-online-input-method-pali
  - go get github.com/siongui/gopherjs-i18n
  - go get github.com/siongui/gopherjs-input-suggest
  - go get github.com/siongui/paliDataVFS
  - go get github.com/gopherjs/gopherjs
script:
  - make dir
  - make html
  - make scss
  - make js
