dist: bionic
language: go
go:
  - 1.12.17
addons:
  apt:
    packages:
    - wget
    - make
    - git
    - gettext
install:
  - make install
script:
  # build website/ content for dictionary.online-dhamma.net first
  - make po2mo
  - make dir
  - make html
  - make js
  - make cname
  - make symlink
  # copy dictionary.online-dhamma.net content to website2/
  # website2/ contains the content of dictionary.online-dhamma.net
  # ref for copy symlink: https://unix.stackexchange.com/a/56170
  - cp -RP website/ website2
  # overwrite website/ content such that it becomes content of dictionary.sutta.org
  - echo "dictionary.sutta.org" > website/CNAME
  - make htmlsutta
# website/ is for dictionary.sutta.org, and website2 is for dictionary.online-dhamma.net
deploy:
  - provider: pages
    repo: siongui/dictionary.online-dhamma.net
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website2
    on:
      branch: master
  - provider: pages
    repo: siongui/dictionary.sutta.org
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website
    on:
      branch: master
