dist: bionic
language: go
go:
  - 1.12.17
addons:
  apt:
    packages:
    - wget
    - make
    - git
    - gettext
install:
  - make install
script:
  # build website/ content for dictionary.online-dhamma.net
  - make make-dhamma-basic
  # move dictionary.online-dhamma.net to website2/
  - mv website/ website2
  # build website/ content for dictionary.sutta.org
  - make make-sutta
after_success:
  - make custom_github_pages_deploy
# dpl v2
#deploy:
#  - provider: pages:git
#    repo: siongui/dictionary.online-dhamma.net
#    token: $GITHUB_TOKEN
#    local_dir: website2
#    on:
#      branch: master
#    edge: true
#    verbose: true
#  - provider: pages:git
#    repo: siongui/dictionary.sutta.org
#    token: $GITHUB_TOKEN
#    local_dir: website
#    on:
#      branch: master
#    edge: true
#    verbose: true
# dpl v1
#deploy:
#  - provider: pages
#    repo: siongui/dictionary.online-dhamma.net
#    skip_cleanup: true
#    keep_history: true
#    github_token: $GITHUB_TOKEN
#    local_dir: website2
#    on:
#      branch: master
#  - provider: pages
#    repo: siongui/dictionary.sutta.org
#    skip_cleanup: true
#    keep_history: true
#    github_token: $GITHUB_TOKEN
#    local_dir: website
#    on:
#      branch: master
