language: go
go:
  - 1.9.2
install:
  - make install
script:
  - make po2mo
  - make dir
  - make html
  - make scss
  - make js
  - make cname
  - make symlink
deploy:
  provider: pages
  repo: siongui/pali-dictionary
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: website
  on:
    branch: master
