dist: bionic
language: go
go:
  - 1.12.17
addons:
  apt:
    packages:
    - wget
    - make
    - git
    - gettext
install:
  - make install
script:
  - make po2mo
  - make dir
  - make html
  - make js
  - make 404html
  - make cname
  - make symlink
  # https://unix.stackexchange.com/a/56170
  - cp -RP website/ website2
  - echo "dictionary.sutta.org" > website2/CNAME
deploy:
  - provider: pages
    repo: siongui/dictionary.online-dhamma.net
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website
    on:
      branch: master
  - provider: pages
    repo: siongui/dictionary.sutta.org
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website2
    on:
      branch: master
