dist: bionic
language: go
go:
  - 1.12.17
addons:
  apt:
    packages:
    - wget
    - make
    - git
    - gettext
install:
  - make install
script:
  - make po2mo
  # build website/ content for dictionary.online-dhamma.net
  - make dir
  - make html
  - make js
  #- make cname
  - make symlink
  # move dictionary.online-dhamma.net content to website2/
  - mv website/ website2
  # build website/ content for dictionary.sutta.org
  - make dir
  - make htmlsutta
  - make js
  #- echo "dictionary.sutta.org" > website/CNAME
  - make symlink
# website/ is dictionary.sutta.org, and website2/ is dictionary.online-dhamma.net
deploy:
  - provider: pages
    repo: siongui/dictionary.online-dhamma.net
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website2
    on:
      branch: master
    verbose: true
    fqdn: dictionary.online-dhamma.net
  - provider: pages
    repo: siongui/dictionary.sutta.org
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website
    on:
      branch: master
    verbose: true
    fqdn: dictionary.sutta.org
