language: go
go:
  - 1.8.3
install:
  - go get github.com/siongui/gopalilib/dicutil
  - go get github.com/wellington/go-libsass
  - go get github.com/siongui/go-online-input-method-pali
  - go get github.com/siongui/gopherjs-i18n
  - go get github.com/siongui/gopherjs-input-suggest
  - go get github.com/siongui/paliDataVFS
  - go get github.com/gopherjs/gopherjs
script:
  - mkdir -p ${WEBSITE_DIR}
  - go run setup/dicsetup.go -action=html -isdev=true > ${WEBSITE_DIR}/index.html
  - wget -O ${SCSS_DIR}/_normalize500.scss https://necolas.github.io/normalize.css/5.0.0/normalize.css
  - go run setup/scss.go -scsspath=${SCSS_PATH} -scssdir=${SCSS_DIR} -csspath=${WEBSITE_DIR}/style.css
  - gopherjs build gopherjs/*.go -o ${WEBSITE_DIR}/pali.js
env:
  global:
    - WEBSITE_DIR=website
    - SCSS_DIR=theme/styling
    - SCSS_PATH=${SCSS_DIR}/style.scss
