dist: bionic
language: go
go:
  - 1.12.17
addons:
  apt:
    packages:
    - wget
    - make
    - git
    - gettext
install:
  - make install
script:
  - make po2mo
  - make dir
  - make html
  - make js
  - make cname
  - make symlink
deploy:
  - provider: pages
    repo: siongui/pali-dictionary
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website
    on:
      branch: master
  - provider: pages
    repo: siongui/dictionary.sutta.org
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website
    on:
      branch: master
